### ISSUE TITLE
Implement coverage badge

### ISSUE THREAD

**Issue by peerchemist** [PeerAssets/pypeerassets#107]
https://github.com/dbrgn/coverage-badge

**Comment by belovachap** [comment]
I've heard that Coveralls is pretty popular https://coveralls.io/
I also ran into this other hosted coverage service: https://codecov.io/

**Comment by peerchemist** [comment]
So how do we do it?

**Comment by belovachap** [comment]
I'll try to get coveralls running today just to see, but I believe we add an additional step to our Travis CI build script that runs the coverage tool and then pushes the results to coveralls.io (they take care of hosting the cute button). I'm assuming I'll need you (@peerchemist) to login to their website and "enable" something but I'll ping you once I get that far :)
