### ISSUE TITLE
Prevent Issuance from subscribed and standard P2TH accounts

### ISSUE THREAD

**Issue by saeveritt** [PeerAssets/pypeerassets#28]
Since there will be available UTXO's from imported accounts associated with subscribed decks and standard P2TH accounts there will need to be restrictions on issuance coming from these accounts.

**Comment by peerchemist** [comment]
fixed with https://github.com/PeerAssets/pypeerassets/commit/1e8d844fa069ac59566955d7021050b1b95dd097
