### ISSUE TITLE
Kutil WIF import is broken.

### ISSUE THREAD

**Issue by peerchemist** [PeerAssets/pypeerassets#3]
Kutil properly creates WIF:
> "92GfU9x38TDQ4fhoowJA1B4xLwDdtSTjQCUBEaQxa2juwK77x9U"

Peercoin wallet properly imports this WIF and reports pubkey:
> "pubkey" : "045c9c65281e72627ce6016b725f9b34f18962d4904576a777f280f48fd48ccd529b8eb52e1054489c9942c69fcaa38e5090aef040d9db8177f452901a9460d15d"

Now try to import the same WIF to Kutil again:
> mykey = Kutil(wif="92GfU9x38TDQ4fhoowJA1B4xLwDdtSTjQCUBEaQxa2juwK77x9U")
> hexlify(mykey._pubkey).decode("utf-8")
> '048efda87d902a625338a159adf578a281ac6c89c955ac770e05ef5dc9658a26b4d05942f252781732df986fd6b3af1f4e7df4583260bc2eb4a30a68e4c8104cb3'

**Comment by hrobeers** [comment]
Make sure to cover things like this with unit tests.
So accidental breakage get's detected early.
Preferably use test driven development instead of doing manual console tests while developing.
