### ISSUE TITLE
RpcNode object has no attribute 'network_p2th'

### ISSUE THREAD

**Issue by saeveritt** [PeerAssets/pypeerassets#78]
https://github.com/PeerAssets/pypeerassets/blob/8cde356ce51384c1c3e5a8923a1ea7c4e264000b/pypeerassets/provider/rpcnode.py#L31

AttributeError: 'RpcNode' object has no attribute 'network_p2th'

**Comment by peerchemist** [comment]
Try: `provider.pa_parameters.P2TH_addr`

**Comment by saeveritt** [comment]
Issue solved.
